name: Build

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: self-hosted

    container:
      image: ${{ vars.DOCKER_REGISTRY }}/godot:4.6.2-stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Export project
        run: |
          rm -rf $HOME/.local/share/godot/ && mkdir -p $HOME/.local/share/godot/
          mv /opt/godot/* $HOME/.local/share/godot/

          rm -rf ../build && mkdir ../build
          godot --headless --check-only project.godot
          godot --headless --export-release 'Web' project.godot
          ls -l ../build
