name: Build and Publish

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

env:
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

jobs:
  publish:
    name: Build and Publish
    runs-on: self-hosted

    container:
      image: ${{ vars.DOCKER_REGISTRY }}/godot:4.6.2-stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Mark repository as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Export project
        run: |
          rm -rf $HOME/.local/share/godot/ && mkdir -p $HOME/.local/share/godot/
          mv /opt/godot/* $HOME/.local/share/godot/

          rm -rf ../build && mkdir ../build
          godot --headless --export-release 'Web' project.godot
          ls -l ../build
          cd ../build
          zip $GITHUB_WORKSPACE/build.zip *

      - name: Publish to dev stream
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          butler push build.zip ${{ secrets.ITCH_PROJECT_NAME}}:dev --userversion $(git rev-parse --short ${{ github.sha }})

      - name: Publish to prod stream
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          butler push build.zip ${{ secrets.ITCH_PROJECT_NAME}}:prod --userversion ${{ github.ref_name }}